### ISSUE TITLE
Policy string

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-create#1]
Should this 
'{"Version": "2012-10-17","Statement": [{"Effect": "Allow","Principal": {"Service": "eks.amazonaws.com"},"Action": "sts:AssumeRole"}]}'

be 

policy = {"Version": "2012-10-17",
                "Statement": [
                    {"Effect": "Allow",
                      "Principal": {"Service": "eks.amazonaws.com"},
                      "Action": "sts:AssumeRole"}
                   ]
                 }
policy = str(policy)
? 
To increase readability

what do you think?

**Comment by harshadpitkar** [comment]
Updated the format for all occurences
