### ISSUE TITLE
--kind=kubernetes,cluster

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-create#7]
As AWS came out with parallel cluster we may want to add a kind option so that we specify a kind.

we also need to add it to the config file as

kind: kubernetes

kind: cluster

this way we can enhance the ability to also use  to a parallel cluster def in the future

**Comment by harshadpitkar** [comment]
Config file now considers the option for PCS
cloudmesh:
  cluster:
    aws:
      kind: PCS #| kubernetes
